### ISSUE TITLE
Error on dumping recipes in ATM9

### ISSUE THREAD

**Issue by TheStraying11** [RedstoneWizard08/RecipeDumper#2]
when dumping the macerator recipe from gregtech the mod seems to create an invalid path (with a `:`)

```
Command exception: /dump recipes
java.nio.file.InvalidPathException: Illegal char <:> at index 13: recipes/gtceu:macerator/minecraft/air.json
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.resolve(Path.java:515)
	at TRANSFORMER/recipedumper@0.3.0/redstonedev.recipedumper.DumpWriter.writeDump(DumpWriter.java:24)
	at TRANSFORMER/recipedumper@0.3.0/redstonedev.recipedumper.DumpWriter.writeRecipeDump(DumpWriter.java:80)
	at TRANSFORMER/recipedumper@0.3.0/redstonedev.recipedumper.Dumper.dumpRecipes(Dumper.java:50)
	at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.m_242674_(Commands.java:257)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1246)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerGamePacketListenerImpl.java:1223)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TheStraying11** [comment]
steps to reproduce: 
    - load All The Mods 9 (possibly anything with gregtech, possibly any mod)
    - load single player world
    - /dump recipes

**Comment by RedstoneWizard08** [comment]
I'll take a look. That's extremely weird, mods shouldn't be able to use a `:` in a `ResourceLocation` even if it's not for a standard ID.

**Comment by RedstoneWizard08** [comment]
I think I found the issue. I'll try to push a patch either tonight or tomorrow, it depends on school xD

**Comment by RedstoneWizard08** [comment]
Sorry, homework has been bad but I'll update it today.

**Comment by RedstoneWizard08** [comment]
Sorry, homework has been bad but I'll update it today.

**Comment by RedstoneWizard08** [comment]
Quick update: for some reason the mod is having issues compiling. I'm working on it.
